"""
Add `eye_size` / `eye_distance` follower shape keys to the eye-region meshes
(eyeball, tearline, eye occlusion), so those separate objects track the body
morphs instead of staying behind (which reads as cross-eyed / floating eyes).

The MorphController already drives same-named keys on every mesh, so once
these keys exist no other code changes are needed.

Magnitudes are matched to the body morphs generated by
generate_customization_morphs.py:
  - eye_distance: body moves socket verts +-0.6 units in X at slider 1.0
  - eye_size:     body scales the opening radially ~35% in X/Z at slider 1.0;
                  the eyeball scales uniformly (sphere must stay spherical),
                  tearline/occlusion scale in X/Z like the body.

Usage:
  blender --background --python add_eye_follow_morphs.py -- \
      <in.blend> <out.blend> [eye_object] [tearline_object] [occlusion_object]
"""
import bpy
import numpy as np
import sys

argv = sys.argv
argv = argv[argv.index("--") + 1:] if "--" in argv else []
blend_in, blend_out = argv[0], argv[1]
EYE_NAME = argv[2] if len(argv) > 2 else "CC_Base_Eye"
TEARLINE_NAME = argv[3] if len(argv) > 3 else "CC_Base_TearLine"
OCCLUSION_NAME = argv[4] if len(argv) > 4 else "CC_Base_EyeOcclusion"

EYE_DISTANCE_SHIFT = 0.6   # matches body morph magnitude
EYE_SIZE_SCALE = 0.30      # eyeball uniform scale at slider 1.0
EYE_SIZE_SCALE_XZ = 0.35   # tearline/occlusion X/Z scale (matches body 0.35)

bpy.ops.wm.open_mainfile(filepath=blend_in)

# Eyeball centers define the pivot for all three meshes.
eye_obj = bpy.data.objects[EYE_NAME]
en = len(eye_obj.data.vertices)
eye_co = np.zeros(en * 3, dtype=np.float64)
eye_obj.data.vertices.foreach_get("co", eye_co)
eye_co = eye_co.reshape(en, 3)
center_pos = eye_co[eye_co[:, 0] > 0].mean(axis=0)
center_neg = eye_co[eye_co[:, 0] < 0].mean(axis=0)


def get_basis(obj):
    mesh = obj.data
    n = len(mesh.vertices)
    if mesh.shape_keys is None:
        obj.shape_key_add(name="Basis", from_mix=False)
    basis = mesh.shape_keys.key_blocks[0]
    co = np.zeros(n * 3, dtype=np.float64)
    basis.data.foreach_get("co", co)
    return co.reshape(n, 3)


def set_key(obj, name, new_co):
    mesh = obj.data
    kb = mesh.shape_keys.key_blocks.get(name)
    if kb is None:
        kb = obj.shape_key_add(name=name, from_mix=False)
    kb.slider_min = -1.0
    kb.slider_max = 1.0
    kb.value = 0.0
    kb.data.foreach_set("co", new_co.reshape(-1).astype(np.float32))
    mesh.update()


for obj_name, uniform in [(EYE_NAME, True), (TEARLINE_NAME, False),
                          (OCCLUSION_NAME, False)]:
    obj = bpy.data.objects.get(obj_name)
    if obj is None:
        print(f"WARNING: {obj_name} not found, skipping")
        continue
    basis_co = get_basis(obj)
    X = basis_co[:, 0]
    center = np.where((X > 0)[:, None], center_pos, center_neg)

    # eye_distance: rigid sideways shift per side
    dist_co = basis_co.copy()
    dist_co[:, 0] += np.sign(X) * EYE_DISTANCE_SHIFT
    set_key(obj, "eye_distance", dist_co)

    # eye_size: scale about the eyeball center
    radial = basis_co - center
    if uniform:
        size_co = basis_co + radial * EYE_SIZE_SCALE
    else:
        size_co = basis_co.copy()
        size_co[:, 0] += radial[:, 0] * EYE_SIZE_SCALE_XZ
        size_co[:, 2] += radial[:, 2] * EYE_SIZE_SCALE_XZ
    set_key(obj, "eye_size", size_co)

    print(f"{obj_name}: added eye_distance, eye_size "
          f"({'uniform' if uniform else 'X/Z'} scaling)")

bpy.ops.wm.save_as_mainfile(filepath=blend_out)
print("Saved:", blend_out)
